app_list = [
            'COMMERCIAL FLOOR*',
            'COMMERCIAL FLOOR',
            'RESIDENTIAL FLOOR',
            'RESIDENTIAL AND COMMERCIAL WALL',
            'SHOWER WALL',
            'SHOWER FLOOR',
            'STEAM SHOWER',
            'KITCHEN COUNTER',
            'STOVE AREA',
            'FIREPLACE FACADE',
            'COVERED EXTERIOR WALL FREEZING CLIMATES',
            'COVERED EXTERIOR WALL NON-FREEZING CLIMATES',
            'UNCOVERED EXTERIOR WALL FREEZING CLIMATES',
            'UNCOVERED EXTERIOR WALL NON-FREEZING CLIMATES',
            'COVERED EXTERIOR FLOOR FREEZING CLIMATES',
            'COVERED EXTERIOR FLOOR NON-FREEZING CLIMATES',
            'UNCOVERED EXTERIOR FLOOR FREEZING CLIMATES',
            'UNCOVERED EXTERIOR FLOOR NON-FREEZING CLIMATES',
            'POOL DECK',
            'POOL WATERLINE',
            'INSIDE POOL',
            'SPA / HOT TUB',
            'UV/ SUN EXPOSURE SENSITIVE',
            'Finish',
            'Edge Detail',
            'Grout Joint Width (in.)',
            'Nominal Size (in.)',
            'Thickness (in.)*',
            'Shade Variation',
            'DCOF AcuTest WET',
        ]
